version: '3.3'

networks:
  internal_network:

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: '${APP_NAME}-server'
    ports:
      - '${APP_PORT}:5000'
    working_dir: /opt/myflaskapp/app
    environment:
      - 'DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db_server:${DB_PORT}/${POSTGRES_DB}'
    depends_on:
      - db
    networks:
      - internal_network

  db:
    image: postgres
    container_name: '${APP_NAME}-db'
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal_network

  adminer:
    image: adminer
    depends_on: 
      - db
    restart: always
    ports:
      - '${APP_DB_ADMINER_PORT}:8080'
    networks:
      - internal_network

volumes:
  db_data:
